### ISSUE TITLE
Tags appear in content of generated markdown cards

### ISSUE THREAD

**Issue by jyrodgers** [guiferviz/mnemocards#4]
When generating the example markdown cards in `examples/computer_science' I see the tags  in the content of card like this:

![Screen Shot 2020-04-29 at 13 35 18](https://user-images.githubusercontent.com/4572538/80644301-4769f600-8a1e-11ea-9cfe-0393548f6f3c.png)

This does not match the screenshots in the Readme. 

It seems like this line is combining this information which is then added to the content: 
https://github.com/guiferviz/mnemocards/blob/55c75984d9f768f2c60ea621aca71d943df887c2/mnemocards/builders/markdown_card_builder.py#L169

I changed this line to 

```python
header = "" + header
```

and that generated what I expected.

**Comment by guiferviz** [comment]
Yes, it's something that I added after taking the screenshoots.
The reason of this is to avoid things like "in Python" in the example card. Imagine that you are also learning another programming language, you will have another question like this one: "How can you check if a file exists in C++?". You will need to specify the programming language in each card. Of course you can create a different deck, but Anki is not prepared to work with a lot of decks and I already have a lot.

I was thinking to add a property in `card_config.json`, something like:
```json
{
    "type": "markdown",
    "file": "my_cards.cards",
    "show_tags": true
}
```
So you can control from there that feature. What do you think?
