### ISSUE TITLE
Script /docker/run.sh doesn't work.

### ISSUE THREAD

**Issue by Otter-man** [guiferviz/mnemocards#5]
Script for docker doesn't work, because docker image doesn't have "latest" tag.
```
$ sudo ./run.sh
Unable to find image 'guiferviz/mnemocards:latest' locally
docker: Error response from daemon: manifest for guiferviz/mnemocards:latest not found: manifest unknown: manifest unknown.
```
You also can't pull image from docker hub with `docker pull guiferviz/mnemocards` for the same reason.

Current workaround:
Rewrite line `guiferviz/mnemocards` in `run.sh` to `guiferviz/mnemocards:v0.1.3` the script starts working.

Solution:
Add image with `latest` tag https://hub.docker.com/r/guiferviz/mnemocards/tags

**Comment by guiferviz** [comment]
Thanks @Otter-man! Thank you for your detailed issue.
Adding the latest tag and automating the image build with each new commit to master.

Sorry about the late response. Let me know if you have more problems or you can to contribute :)
